### ISSUE TITLE
Simultaneous saving of all data?

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#150]
We may want a way to allow the user to save training data, test data, calibration data, and parameter values all at once. See #69, #113, #114.

**Comment by damellis** [comment]
Removing this from the Cleanup milestone as I think we can get away without it for now.

**Comment by damellis** [comment]
One way to do this would be to have the user specify the name of the directory to save or load, and have fixed file names within the directory for each type of data (training, test, etc.).

**Comment by nebgnahz** [comment]
Commit https://github.com/damellis/ESP/commit/dee80cce5a0d2a9cb06951d79ada75a538feefdb makes the attempt to enable saving and loading all the data at the same time.

The abstraction is called an ESP session which includes calibration data, training data, test data and the pipeline (could have been trained).

The commit also unified the implementation: for every single type of data, we have `saveXWithPrompt`/`saveX` and `loadXWithPrompt`/`loadX`. `saveAll` and `loadAll` uses a pre-defined filename appended to a user selected directory name. All functions call `setStatus` which currently changes the status message so that the user will have an idea of what's going on.

`loadAll` and `saveAll` are bound to `L` and `S` keys.

**Comment by nebgnahz** [comment]
Tunable parameters are not yet implemented.

**Comment by damellis** [comment]
This all looks good. What do you think about making save all the default on exit?

**Comment by damellis** [comment]
I think we can call this finished.
