### ISSUE TITLE
Tunable parameter text appears double size on larger monitors.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#161]
My monitor is, it looks like, 2560 x 1600 pixels.

![screen shot 2016-04-25 at 3 13 43 pm](https://cloud.githubusercontent.com/assets/405058/14800699/55e516c8-0af8-11e6-83e3-0cd8743aa3af.png)

**Comment by nebgnahz** [comment]
This is probably due to https://github.com/braitsch/ofxDatGui/blob/6dd5138801bb23a291dc0d11453e08dca6736b52/src/themes/ofxDatGuiTheme.h#L27.

Also I changed the default size https://github.com/nebgnahz/ofxDatGui/commit/4940fa52607d40aff9d9942d548b1b2ae119205e#diff-bbdd6e06a8e880afea8b672cf2a54ce7R216.

**Comment by damellis** [comment]
Hmm… I think openFrameworks does have a way to query the multiplier used for the screen (e.g. “1” for normal screens, “2” for retina). But this is not necessarily a high priority.
